import type { Metadata } from "next";

import { ReportDocument } from "@/components/report/report-document";
import { normalizeReportSymbol, reportSymbols } from "@/lib/report-paths";

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

interface ReportPageProps {
  params: Promise<{
    symbol: string;
  }>;
}

export function generateStaticParams() {
  return reportSymbols.map((symbol) => ({ symbol }));
}

export async function generateMetadata({ params }: ReportPageProps): Promise<Metadata> {
  const { symbol } = await params;
  const reportSymbol = normalizeReportSymbol(symbol);

  return {
    title: `${reportSymbol} Deep Dive Report | FX-AlphaLab`,
    description: `${reportSymbol} live daily market report generated by the FX-AlphaLab inference pipeline.`,
  };
}

async function fetchReportHtml(symbol: string): Promise<string | null> {
  try {
    const res = await fetch(`${API_BASE}/reports/html/${symbol}/latest`, {
      next: { revalidate: 3600 }, // ISR: re-fetch at most once per hour
    });
    if (!res.ok) return null;
    return await res.text();
  } catch {
    return null;
  }
}

export default async function ReportPage({ params }: ReportPageProps) {
  const { symbol } = await params;
  const reportSymbol = normalizeReportSymbol(symbol);
  const html = await fetchReportHtml(reportSymbol);

  if (!html) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <div className="text-center space-y-3">
          <h1 className="text-2xl font-semibold">{reportSymbol} Report</h1>
          <p className="text-muted-foreground">
            No report available yet. Run the inference pipeline to generate one.
          </p>
          <p className="text-xs text-muted-foreground font-mono">
            POST /admin/inference/run — or run: python generate_report.py
          </p>
        </div>
      </div>
    );
  }

  return <ReportDocument html={html} symbol={reportSymbol} />;
}
